# Generated by Django 2.0.3 on 2018-05-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stuNo', models.IntegerField(verbose_name='学号')),
                ('stuName', models.CharField(max_length=32, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('Female', '女'), ('Male', '男')], max_length=10, null=True, verbose_name='性别')),
                ('nation', models.CharField(max_length=10, verbose_name='民族')),
                ('academy', models.CharField(max_length=20, verbose_name='学院')),
                ('major', models.CharField(max_length=20, verbose_name='专业')),
                ('stuClass', models.CharField(max_length=10, verbose_name='班级')),
                ('stuGrade', models.CharField(max_length=10, verbose_name='年级')),
            ],
        ),
        migrations.CreateModel(
            name='StuInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stuNo', models.IntegerField(verbose_name='学号')),
                ('stuName', models.CharField(max_length=32, verbose_name='姓名')),
                ('entrance_score', models.IntegerField(verbose_name='入学成绩')),
                ('family_status', models.CharField(max_length=10, verbose_name='家庭状况')),
                ('attendance', models.CharField(max_length=10, verbose_name='考勤')),
                ('learn_time', models.IntegerField(verbose_name='每日学习时间')),
                ('grade_point', models.FloatField(verbose_name='平均绩点')),
                ('last_term_score', models.CharField(max_length=10, verbose_name='上学期综合成绩')),
                ('now_term_score', models.CharField(max_length=10, verbose_name='本学期综合成绩')),
            ],
        ),
    ]
