# Generated by Django 2.0.3 on 2018-05-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuinfo',
            name='attendance',
            field=models.CharField(max_length=10, null=True, verbose_name='考勤'),
        ),
        migrations.AlterField(
            model_name='stuinfo',
            name='entrance_score',
            field=models.IntegerField(null=True, verbose_name='入学成绩'),
        ),
        migrations.AlterField(
            model_name='stuinfo',
            name='family_status',
            field=models.CharField(max_length=10, null=True, verbose_name='家庭状况'),
        ),
        migrations.AlterField(
            model_name='stuinfo',
            name='grade_point',
            field=models.FloatField(null=True, verbose_name='平均绩点'),
        ),
        migrations.AlterField(
            model_name='stuinfo',
            name='last_term_score',
            field=models.CharField(max_length=10, null=True, verbose_name='上学期综合成绩'),
        ),
        migrations.AlterField(
            model_name='stuinfo',
            name='learn_time',
            field=models.IntegerField(null=True, verbose_name='每日学习时间'),
        ),
        migrations.AlterField(
            model_name='stuinfo',
            name='now_term_score',
            field=models.CharField(max_length=10, null=True, verbose_name='本学期综合成绩'),
        ),
        migrations.AlterField(
            model_name='stuinfo',
            name='stuName',
            field=models.CharField(max_length=32, null=True, verbose_name='姓名'),
        ),
    ]
