# Generated by Django 2.0.3 on 2018-05-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_student_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuinfo',
            name='warning',
            field=models.BooleanField(default=1, verbose_name='预警(是/否)'),
            preserve_default=False,
        ),
    ]
