# Generated by Django 2.0.3 on 2018-05-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_stuinfo_warning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuinfo',
            name='entrance_score',
            field=models.CharField(max_length=10, null=True, verbose_name='入学成绩'),
        ),
        migrations.AlterField(
            model_name='stuinfo',
            name='grade_point',
            field=models.CharField(max_length=10, null=True, verbose_name='平均绩点'),
        ),
    ]
