# Generated by Django 2.0.3 on 2018-05-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20180506_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生信息', 'verbose_name_plural': '学生信息'},
        ),
        migrations.AlterModelOptions(
            name='stuinfo',
            options={'verbose_name': '数据集', 'verbose_name_plural': '数据集'},
        ),
        migrations.AlterField(
            model_name='stuinfo',
            name='learn_time',
            field=models.IntegerField(null=True, verbose_name='每日课后学习时间'),
        ),
        migrations.AlterField(
            model_name='stuinfo',
            name='warning',
            field=models.CharField(max_length=10, null=True, verbose_name='预警(是/否)'),
        ),
    ]
