# Generated by Django 2.0.3 on 2018-04-30 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('Female', '女'), ('Male', '男')], max_length=10, null=True, verbose_name='性别')),
                ('date_join', models.DateField(auto_now=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '用户数据',
                'verbose_name_plural': '用户数据',
                'permissions': (('view_users', 'Can see available userlist'),),
            },
        ),
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='部门')),
                ('remarks', models.CharField(blank=True, max_length=64, verbose_name='备注')),
                ('owner', models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '组',
                'verbose_name_plural': '部门',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, to='users.AccountGroup', verbose_name='部门或组'),
        ),
    ]
